"""Local bootstrap helpers for install-time configuration and verification."""

from __future__ import annotations

import json
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any


def provider_runtime_base_url(kind: str, base_url: str) -> str:
    normalized = base_url.rstrip("/")
    if kind == "anthropic":
        return normalized if normalized.endswith("/messages") else f"{normalized}/messages"
    return normalized if normalized.endswith("/responses") else f"{normalized}/responses"


def build_local_runtime_profile(
    *,
    storage_root: str,
    service_port: int,
    provider_kind: str,
    provider_default_model: str,
    provider_base_url: str,
    software_repo_path: str = "",
) -> dict[str, Any]:
    return {
        "storage_root": storage_root,
        "service": {
            "host": "127.0.0.1",
            "port": service_port,
            "token_env": "CEOS_OPERATOR_TOKEN",
        },
        "provider": {
            "kind": provider_kind,
            "api_key_env": "CEOS_API_KEY",
            "base_url_env": "CEOS_API_BASE_URL",
            "default_model": provider_default_model,
            "base_url": provider_base_url,
        },
        "external_backend": {
            "kind": "sqlite",
            "url": "",
            "namespace": "ceos",
        },
        "shared_state_backend": {
            "kind": "sqlite",
            "url": "",
            "schema": "public",
        },
        "software_control": {
            "enabled": True,
            "source_kind": "cli-anything",
            "repo_path": software_repo_path,
            "allow_auto_task": True,
            "macro_enabled": True,
            "macro_default_approval": True,
        },
        "observability": {
            "enabled": True,
            "snapshot_interval_seconds": 60,
            "prometheus_enabled": True,
            "alerts_enabled": True,
            "history_window_hours": 24,
        },
        "maintenance": {
            "daemon_enabled": True,
            "poll_interval_seconds": 30,
            "heartbeat_seconds": 30,
            "lease_seconds": 300,
        },
    }


def write_local_runtime_profile(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


def write_local_env_file(
    path: Path,
    *,
    operator_token: str,
    storage_root: str,
    api_key: str = "",
    base_url: str = "",
    provider_kind: str = "deterministic",
    default_model: str = "",
    cli_anything_repo_path: str = "",
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Local environment generated by Contract-Evidence OS install.sh --init-config",
        f'export CEOS_OPERATOR_TOKEN="{operator_token}"',
        f'export CEOS_STORAGE_ROOT="{storage_root}"',
        f'export CEOS_PROVIDER_KIND="{provider_kind}"',
    ]
    if api_key:
        lines.append(f'export CEOS_API_KEY="{api_key}"')
    else:
        lines.append('# export CEOS_API_KEY=""')
    if base_url:
        lines.append(f'export CEOS_API_BASE_URL="{base_url}"')
    else:
        lines.append('# export CEOS_API_BASE_URL=""')
    if default_model:
        lines.append(f'export CEOS_DEFAULT_MODEL="{default_model}"')
    else:
        lines.append('# export CEOS_DEFAULT_MODEL=""')
    if cli_anything_repo_path:
        lines.append(f'export CEOS_CLI_ANYTHING_REPO_PATH="{cli_anything_repo_path}"')
    else:
        lines.append('# export CEOS_CLI_ANYTHING_REPO_PATH=""')
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def verify_provider_configuration(
    *,
    provider_kind: str,
    api_key: str,
    base_url: str,
    timeout_seconds: float = 5.0,
) -> dict[str, Any]:
    if provider_kind == "deterministic":
        return {"ok": True, "provider_kind": provider_kind, "status": "skipped", "detail": "deterministic provider selected"}
    if not api_key:
        return {"ok": False, "provider_kind": provider_kind, "status": "missing_api_key", "detail": "API key is required for live provider verification"}
    normalized = base_url.rstrip("/")
    if provider_kind == "anthropic":
        request = urllib.request.Request(
            normalized,
            method="HEAD",
            headers={
                "x-api-key": api_key,
                "anthropic-version": "2023-06-01",
            },
        )
    else:
        request = urllib.request.Request(
            f"{normalized}/models",
            method="GET",
            headers={
                "Authorization": f"Bearer {api_key}",
            },
        )
    try:
        with urllib.request.urlopen(request, timeout=timeout_seconds) as response:
            return {
                "ok": 200 <= response.status < 300,
                "provider_kind": provider_kind,
                "status": response.status,
                "detail": "provider verification succeeded",
            }
    except urllib.error.HTTPError as exc:
        return {
            "ok": False,
            "provider_kind": provider_kind,
            "status": exc.code,
            "detail": exc.read().decode("utf-8", errors="ignore") or "provider verification failed",
        }
    except urllib.error.URLError as exc:
        return {
            "ok": False,
            "provider_kind": provider_kind,
            "status": "network_error",
            "detail": str(exc.reason),
        }
