from datetime import UTC, datetime

from contract_evidence_os.agents.models import CapabilityPassport
from contract_evidence_os.audit.models import AuditEvent, ExecutionReceipt
from contract_evidence_os.contracts.models import ContractDelta, ContractLattice, TaskContract
from contract_evidence_os.evidence.models import (
    ClaimRecord,
    EvidenceEdge,
    EvidenceNode,
    SourceRecord,
    ValidationReport,
)
from contract_evidence_os.evolution.models import CanaryRun, EvaluationRun, EvolutionCandidate
from contract_evidence_os.memory.models import MemoryPromotionRecord, MemoryRecord, SkillCapsule
from contract_evidence_os.planning.models import ExecutionBranch, PlanEdge, PlanGraph, PlanNode, PlanRevision, SchedulerState
from contract_evidence_os.policy.models import ApprovalDecision, ApprovalRequest, RemoteApprovalOperation
from contract_evidence_os.recovery.models import CheckpointRecord, IncidentReport
from contract_evidence_os.runtime.auth import (
    AuthFailureEvent,
    CredentialRotationRecord,
    ServiceCredential,
    ServicePrincipal,
    ServiceTrustRecord,
)
from contract_evidence_os.runtime.backends import (
    BackendCapabilityDescriptor,
    BackendHealthRecord,
    BackendPressureSnapshot,
    CoordinationBackendDescriptor,
    QueueBackendDescriptor,
)
from contract_evidence_os.runtime.budgeting import (
    BudgetConsumptionRecord,
    BudgetEvent,
    BudgetLedger,
    BudgetPolicy,
)
from contract_evidence_os.runtime.coordination import (
    HostRecord,
    LeaseContentionRecord,
    LeaseExpiryForecast,
    LeaseRenewalPolicy,
    LeaseTransferRecord,
    OwnershipConflictEvent,
    RenewalAttemptRecord,
    WorkStealDecision,
    WorkStealPolicy,
    WorkerEndpointRecord,
    WorkerHostBinding,
)
from contract_evidence_os.runtime.governance import (
    ConcurrencyState,
    ExecutionModeState,
    GovernanceEvent,
    ProviderSelectionPolicy,
    ProviderScorecard,
    RoutingDecisionRecord,
    RoutingPolicy,
    ToolScorecardView,
)
from contract_evidence_os.runtime.provider_pool import (
    ProviderFairnessPolicy,
    ProviderFairnessRecord,
    ProviderPoolBalancePolicy,
    ReservationPolicy,
    SustainedPressurePolicy,
)
from contract_evidence_os.runtime.providers import ProviderCapabilityRecord, ProviderUsageRecord, RoutingReceipt
from contract_evidence_os.tools.models import ToolInvocation, ToolResult, ToolSpec


def _now() -> datetime:
    return datetime(2026, 4, 17, 0, 0, tzinfo=UTC)


def model_instances() -> list[object]:
    contract = TaskContract(
        version="1.0",
        contract_id="contract-001",
        user_goal="Read a file and extract mandatory constraints.",
        normalized_goal="Extract mandatory constraints from an attached file.",
        deliverables=["structured_constraint_summary"],
        hard_constraints=["cite supporting evidence"],
        soft_preferences=["concise wording"],
        forbidden_actions=["delete audit history"],
        success_criteria=["at least two supported facts"],
        failure_conditions=["missing evidence coverage"],
        evidence_requirements=["one source node", "one extraction node"],
        risk_level="moderate",
        approval_required=["destructive_action"],
        budget_limits={"tool_calls": 3},
        time_limits={"seconds": 30},
        tool_limits=["file_retrieval"],
        uncertainty_tolerance="low",
        memory_policy="episodic_first",
        checkpoint_policy="after_each_node",
        evolution_allowed_scope=["prompt_profile", "planning_heuristic"],
    )
    plan_node = PlanNode(
        version="1.0",
        node_id="node-001",
        objective="Read attached file",
        role_owner="Researcher",
        dependencies=[],
        preconditions=["attachment exists"],
        expected_outputs=["source_snapshot", "constraint_extractions"],
        validation_gate="shadow_evidence_coverage",
        fallback_paths=["retry_with_alternate_attachment"],
        budget_cost=1.0,
        status="pending",
        checkpoint_required=True,
        approval_gate=None,
    )
    plan_edge = PlanEdge(
        version="1.0",
        edge_id="edge-001",
        source_node_id="node-001",
        target_node_id="node-002",
        edge_type="verifies",
    )
    evidence_node = EvidenceNode(
        version="1.0",
        node_id="evidence-001",
        node_type="claim",
        content="Audit history must never be deleted.",
        confidence=0.9,
        created_at=_now(),
        metadata={"plan_node_id": "node-001"},
    )
    instances = [
        contract,
        ContractDelta(
            version="1.0",
            delta_id="delta-001",
            contract_id=contract.contract_id,
            previous_version="1.0",
            new_version="1.1",
            changed_fields=["success_criteria"],
            reason="Refined after verification gap",
            author="system",
            timestamp=_now(),
        ),
        ContractLattice(
            version="1.0",
            root_contract_id=contract.contract_id,
            contract_ids=[contract.contract_id, "contract-001-sub"],
            inheritance={contract.contract_id: ["contract-001-sub"]},
            conflicts=[],
        ),
        plan_node,
        plan_edge,
        PlanGraph(version="1.0", graph_id="graph-001", nodes=[plan_node], edges=[plan_edge]),
        PlanRevision(
            version="1.0",
            revision_id="revision-001",
            task_id="task-001",
            plan_graph_id="graph-001",
            cause="provider_error",
            affected_nodes=["node-001"],
            inserted_nodes=["node-001-recovery"],
            superseded_nodes=["node-001"],
            contract_id=contract.contract_id,
            evidence_refs=["evidence-001"],
            approval_refs=[],
            branch_id="branch-recovery",
            created_at=_now(),
        ),
        ExecutionBranch(
            version="1.0",
            branch_id="branch-main",
            task_id="task-001",
            plan_graph_id="graph-001",
            parent_branch_id=None,
            label="Primary branch",
            status="active",
            selected=True,
            cause="initial_plan",
            node_ids=["node-001"],
            created_at=_now(),
        ),
        SchedulerState(
            version="1.0",
            scheduler_id="scheduler-001",
            task_id="task-001",
            plan_graph_id="graph-001",
            active_branch_id="branch-main",
            ready_queue=["node-001"],
            running_nodes=[],
            blocked_nodes=[],
            completed_nodes=[],
            failed_nodes=[],
            deferred_nodes=[],
            status="ready",
            updated_at=_now(),
        ),
        SourceRecord(
            version="1.0",
            source_id="source-001",
            source_type="file",
            locator="/tmp/requirements.txt",
            retrieved_at=_now(),
            credibility=0.95,
            time_relevance=1.0,
            content_hash="abc123",
            snippet="Audit history must never be deleted.",
        ),
        EvidenceNode(
            version="1.0",
            node_id="evidence-000",
            node_type="source",
            content="requirements.txt",
            confidence=1.0,
            created_at=_now(),
            metadata={"source_id": "source-001"},
        ),
        evidence_node,
        EvidenceEdge(
            version="1.0",
            edge_id="eedge-001",
            source_node_id="evidence-000",
            target_node_id="evidence-001",
            edge_type="supports",
        ),
        ClaimRecord(
            version="1.0",
            claim_id="claim-001",
            statement=evidence_node.content,
            claim_type="fact",
            evidence_refs=["evidence-001"],
            status="supported",
        ),
        ValidationReport(
            version="1.0",
            report_id="validation-001",
            contract_id=contract.contract_id,
            validator="ShadowVerifier",
            status="passed",
            confidence=0.9,
            findings=["Evidence coverage satisfied"],
            contradictions=[],
            evidence_refs=["evidence-001"],
        ),
        ToolSpec(
            version="1.0",
            tool_id="file-retrieval",
            name="file_retrieval",
            description="Read a local file with provenance capture.",
            input_schema={"type": "object"},
            output_schema={"type": "object"},
            risk_level="low",
            permission_requirements=["read"],
            retry_policy={"max_attempts": 1},
            timeout_policy={"seconds": 5},
            audit_hooks=["record_invocation"],
            evidence_hooks=["emit_source_record"],
            validation_hooks=["check_file_exists"],
            mock_provider="mock-file-provider",
            simulator_provider="sim-file-provider",
        ),
        ToolInvocation(
            version="1.0",
            invocation_id="invoke-001",
            tool_id="file-retrieval",
            actor="Researcher",
            input_payload={"path": "/tmp/requirements.txt"},
            requested_at=_now(),
        ),
        ToolResult(
            version="1.0",
            invocation_id="invoke-001",
            tool_id="file-retrieval",
            status="success",
            output_payload={"content": "Audit history must never be deleted."},
            error=None,
            started_at=_now(),
            completed_at=_now(),
        ),
        CapabilityPassport(
            version="1.0",
            role_name="Researcher",
            allowed_tools=["file_retrieval", "web_intelligence"],
            forbidden_tools=["destructive_shell"],
            max_risk_level="moderate",
            approval_scope=["read", "execute_low_risk"],
            memory_access_scope=["episodic", "semantic"],
            prompt_profile="research-grounded",
            validation_responsibility="source triangulation",
            output_schema={"type": "object"},
        ),
        ApprovalRequest(
            version="1.0",
            request_id="approval-001",
            contract_id=contract.contract_id,
            action="destructive_action",
            reason="Would remove files",
            requested_scope=["destructive_action"],
            risk_level="high",
            status="pending",
        ),
        ApprovalDecision(
            version="1.0",
            request_id="approval-001",
            decision_id="decision-001",
            approver="Governor",
            status="denied",
            approved_scope=[],
            rationale="Outside contract scope",
            decided_at=_now(),
        ),
        RemoteApprovalOperation(
            version="1.0",
            operation_id="remote-op-001",
            request_id="approval-001",
            task_id="task-001",
            contract_id=contract.contract_id,
            plan_node_id="node-001",
            operator="remote-governor",
            action="approval_decision",
            status="approved",
            rationale="Remote operator approved continuation",
            audit_event_id="audit-001",
            decision_id="decision-001",
            created_at=_now(),
        ),
        AuditEvent(
            version="1.0",
            event_id="audit-001",
            task_id="task-001",
            contract_id=contract.contract_id,
            event_type="tool_invocation",
            actor="Researcher",
            why="Need source evidence",
            evidence_refs=["evidence-001"],
            tool_refs=["file-retrieval"],
            approval_refs=[],
            result="success",
            rollback_occurred=False,
            learning_candidate_generated=False,
            system_version="0.1.0",
            skill_version="initial",
            timestamp=_now(),
        ),
        CheckpointRecord(
            version="1.0",
            checkpoint_id="checkpoint-001",
            task_id="task-001",
            plan_node_id="node-001",
            state_ref="state-001.json",
            created_at=_now(),
            metadata={"phase": "executing"},
        ),
        MemoryRecord(
            version="1.0",
            memory_id="memory-001",
            memory_type="episodic",
            state="provisional",
            summary="Reading requirement files often yields strong evidence seeds.",
            content={"pattern": "file_retrieval_then_extract"},
            sources=["audit-001"],
            created_at=_now(),
            updated_at=_now(),
        ),
        MemoryPromotionRecord(
            version="1.0",
            promotion_id="promotion-001",
            memory_id="memory-001",
            previous_state="validated",
            new_state="promoted",
            rationale="Repeated success across tasks",
            promoted_at=_now(),
        ),
        SkillCapsule(
            version="1.0",
            skill_id="skill-001",
            name="constraint_file_extraction",
            triggering_conditions=["file attachment present"],
            preferred_plan_pattern=["retrieve", "extract", "verify"],
            tool_sequence=["file_retrieval"],
            validation_pattern=["shadow_evidence_coverage"],
            failure_signals=["missing_source"],
            memory_write_policy="write_validated_on_success",
            test_cases=["tests/integration/test_vertical_slice.py"],
            promotion_status="candidate",
            regression_risk="low",
        ),
        EvolutionCandidate(
            version="1.0",
            candidate_id="candidate-001",
            candidate_type="skill_capsule",
            source_traces=["audit-001"],
            target_component="memory.procedural",
            hypothesis="Promoting the retrieval pattern reduces planning time.",
            expected_benefit="faster planning",
            evaluation_suite=["tests/evolution/test_candidate_eval.py"],
            canary_scope="file_tasks_only",
            rollback_plan="revert capsule state",
            promotion_result="pending",
        ),
        EvaluationRun(
            version="1.0",
            run_id="eval-001",
            candidate_id="candidate-001",
            suite_name="offline-core",
            status="passed",
            metrics={"gain": 0.2, "regression_failures": 0},
            started_at=_now(),
            completed_at=_now(),
        ),
        CanaryRun(
            version="1.0",
            run_id="canary-001",
            candidate_id="candidate-001",
            scope="file_tasks_only",
            status="promoted",
            metrics={"success_rate": 1.0},
            started_at=_now(),
            completed_at=_now(),
        ),
        IncidentReport(
            version="1.0",
            incident_id="incident-001",
            task_id="task-001",
            incident_type="tool_failure",
            severity="recoverable",
            summary="File not found",
            recovery_attempted=True,
            resolution="retried_with_checkpoint_restore",
            created_at=_now(),
        ),
        RoutingReceipt(
            version="1.0",
            routing_id="routing-001",
            task_id="task-001",
            role="Researcher",
            workload="extraction",
            risk_level="moderate",
            strategy_name="quality",
            provider_name="primary",
            model_name="gpt-4.1-mini",
            profile="quality-extractor",
            cost_tier="medium",
            attempt_count=1,
            fallback_used=False,
            status="success",
            rationale="risk-sensitive extraction",
            correlation_id="task-001:node-001:provider",
            created_at=_now(),
        ),
        ProviderUsageRecord(
            version="1.0",
            usage_id="provider-usage-001",
            task_id="task-001",
            plan_node_id="node-001",
            correlation_id="task-001:node-001:provider",
            role="Researcher",
            provider_name="primary",
            model_name="gpt-4.1-mini",
            profile="quality-extractor",
            request_summary="Extract facts",
            response_summary="Two grounded statements",
            input_tokens=12,
            output_tokens=7,
            total_tokens=19,
            estimated_cost=0.01,
            latency_ms=42.0,
            retry_count=0,
            fallback_used=False,
            status="success",
            created_at=_now(),
        ),
        ProviderCapabilityRecord(
            version="1.0",
            provider_name="openai_live",
            supported_response_modes=["responses"],
            supports_structured_output=True,
            max_context_hint=200000,
            cost_characteristics="higher",
            rate_limit_characteristics="moderate",
            reliability_inputs={"base": 0.9},
            timeout_defaults={"seconds": 30.0},
            retry_defaults={"max_attempts": 2},
            availability_state="available",
        ),
        ProviderScorecard(
            version="1.0",
            provider_name="openai_live",
            profile="quality-verifier",
            total_requests=5,
            successes=4,
            failures=1,
            structured_output_successes=3,
            retries=1,
            fallbacks=0,
            average_latency_ms=175.0,
            average_cost_per_success=0.03,
            verification_usefulness=0.9,
            continuity_usefulness=0.7,
            last_updated=_now(),
        ),
        ToolScorecardView(
            version="1.0",
            tool_name="file_retrieval",
            variant="live",
            reliability=0.98,
            average_latency_ms=8.0,
            evidence_usefulness=0.9,
            cost_impact=0.01,
            approval_friction=0.0,
        ),
        RoutingDecisionRecord(
            version="1.0",
            decision_id="routing-decision-001",
            task_id="task-001",
            plan_node_id="node-001",
            decision_type="provider",
            chosen_provider="openai_live",
            candidates_considered=["openai_live", "anthropic_live"],
            reason="selected openai_live for verification reliability",
            scorecard_signals={"reliability": 0.8},
            policy_overrides=["verification_bias"],
            degraded_mode_active=False,
            execution_mode="standard",
            created_at=_now(),
        ),
        RoutingPolicy(
            version="1.0",
            policy_id="routing-policy-001",
            name="standard-policy",
            execution_mode="standard",
            provider_policy=ProviderSelectionPolicy(
                version="1.0",
                prefer_live=True,
                require_structured_output=False,
                verification_bias=False,
                prefer_low_cost=False,
                allow_degraded_fallback=True,
            ),
            tool_policy={"prefer_reliable_tools": True},
            degraded_mode_policy={"max_disabled_providers": 1},
        ),
        BudgetPolicy(
            version="1.0",
            policy_id="budget-policy-001",
            task_id="task-001",
            total_budget=1.0,
            verification_reserve=0.2,
            recovery_reserve=0.15,
            continuity_reserve=0.1,
            role_budgets={"Researcher": 0.4},
            provider_budgets={"openai_live": 0.5},
            tool_budgets={"file_retrieval": 0.1},
            created_at=_now(),
        ),
        BudgetLedger(
            version="1.0",
            ledger_id="budget-ledger-001",
            task_id="task-001",
            policy_id="budget-policy-001",
            spent_total=0.2,
            spent_verification=0.05,
            spent_recovery=0.0,
            spent_continuity=0.01,
            remaining_budget=0.8,
            updated_at=_now(),
        ),
        BudgetEvent(
            version="1.0",
            event_id="budget-event-001",
            task_id="task-001",
            event_type="budget_mode_activated",
            summary="low cost mode active",
            payload={"remaining_budget": 0.04},
            created_at=_now(),
        ),
        BudgetConsumptionRecord(
            version="1.0",
            consumption_id="budget-consumption-001",
            task_id="task-001",
            category="provider",
            ref_id="provider-usage-001",
            estimated_cost=0.03,
            actual_cost=0.03,
            justification="verification request",
            created_at=_now(),
        ),
        ExecutionModeState(
            version="1.0",
            mode_id="execution-mode-001",
            task_id="task-001",
            mode_name="low_cost",
            reason="budget pressure",
            active_constraints=["budget pressure"],
            deferred_opportunities=["higher-cost verification"],
            updated_at=_now(),
        ),
        GovernanceEvent(
            version="1.0",
            event_id="governance-event-001",
            task_id="task-001",
            event_type="execution_mode_changed",
            summary="switched to low cost",
            payload={"mode_name": "low_cost"},
            created_at=_now(),
        ),
        ConcurrencyState(
            version="1.0",
            concurrency_id="concurrency-001",
            task_id="task-001",
            max_parallel_nodes=2,
            role_limits={"Researcher": 2},
            provider_limits={"openai_live": 2},
            tool_limits={"file_retrieval": 2},
            active_nodes=["node-001"],
            last_batch_nodes=["node-001", "node-002"],
            backpressure_active=False,
            updated_at=_now(),
        ),
        BackendCapabilityDescriptor(
            version="1.0",
            backend_name="redis",
            backend_kind="redis",
            scope="coordination",
            durability_guarantee="redis + sqlite mirror",
            lease_semantics="fenced current owner",
            heartbeat_support=True,
            ordering_assumption="latest ownership wins",
            reconnect_behavior="re-register after reconnect",
            operational_limit="shared namespace per cluster",
            deployment_assumption="shared backend across hosts",
        ),
        QueueBackendDescriptor(
            version="1.0",
            backend_name="redis",
            backend_kind="redis",
            supports_priority=True,
            supports_leases=True,
            supports_renewal=True,
            supports_dead_letter=True,
            supports_fencing=True,
            durability_guarantee="redis live queue",
        ),
        CoordinationBackendDescriptor(
            version="1.0",
            backend_name="redis",
            backend_kind="redis",
            supports_host_registration=True,
            supports_heartbeats=True,
            supports_fencing=True,
            supports_work_stealing=True,
            lease_semantics="fenced shared ownership",
            durability_guarantee="redis live state + sqlite mirror",
        ),
        BackendHealthRecord(
            version="1.0",
            backend_name="redis",
            backend_kind="redis",
            status="available",
            latency_ms=2.5,
            connected=True,
            updated_at=_now(),
        ),
        BackendPressureSnapshot(
            version="1.0",
            snapshot_id="backend-pressure-001",
            backend_name="redis",
            queue_depth=3,
            active_leases=1,
            active_workers=2,
            delayed_tasks=0,
            created_at=_now(),
        ),
        HostRecord(
            version="1.0",
            host_id="host-a",
            hostname="host-a",
            network_identity="10.0.0.1",
            status="active",
            drain_state="running",
            capabilities=["worker", "verifier"],
            lease_pressure=0.5,
            created_at=_now(),
            last_seen_at=_now(),
        ),
        WorkerHostBinding(
            version="1.0",
            binding_id="binding-001",
            worker_id="worker-1",
            host_id="host-a",
            endpoint_id="endpoint-001",
            status="active",
            bound_at=_now(),
        ),
        WorkerEndpointRecord(
            version="1.0",
            endpoint_id="endpoint-001",
            worker_id="worker-1",
            host_id="host-a",
            address="tcp://host-a:9101",
            protocol="internal",
            status="active",
            last_seen_at=_now(),
        ),
        LeaseRenewalPolicy(
            version="1.0",
            policy_id="renewal-policy-001",
            renew_before_seconds=10,
            max_jitter_seconds=2,
            slow_worker_grace_seconds=5,
            contention_backoff_seconds=3,
            steal_min_age_seconds=20,
            created_at=_now(),
        ),
        RenewalAttemptRecord(
            version="1.0",
            attempt_id="renewal-attempt-001",
            lease_id="lease-001",
            worker_id="worker-1",
            host_id="host-a",
            outcome="renewed",
            latency_ms=4.2,
            previous_expires_at=_now(),
            new_expires_at=_now(),
            created_at=_now(),
            note="renewal-policy-001",
        ),
        LeaseExpiryForecast(
            version="1.0",
            forecast_id="lease-forecast-001",
            lease_id="lease-001",
            seconds_remaining=18.0,
            risk_level="low",
            recommended_action="continue",
            created_at=_now(),
        ),
        LeaseContentionRecord(
            version="1.0",
            contention_id="contention-001",
            lease_id="lease-001",
            current_worker_id="worker-1",
            challenger_worker_id="worker-2",
            decision="accepted",
            reason="owner draining",
            created_at=_now(),
        ),
        WorkStealPolicy(
            version="1.0",
            policy_id="work-steal-policy-001",
            allow_steal_from_draining=True,
            allow_steal_from_stale=True,
            min_lease_age_seconds=20,
            max_pressure_to_keep_owner=0.8,
            protect_verification_capacity=True,
            protect_recovery_capacity=True,
            created_at=_now(),
        ),
        WorkStealDecision(
            version="1.0",
            decision_id="work-steal-001",
            lease_id="lease-001",
            from_worker_id="worker-1",
            to_worker_id="worker-2",
            status="stolen",
            reason="owner draining",
            safety_checks={"lease_old_enough": True},
            created_at=_now(),
        ),
        LeaseTransferRecord(
            version="1.0",
            transfer_id="lease-transfer-001",
            lease_id="lease-001",
            from_worker_id="worker-1",
            to_worker_id="worker-2",
            previous_epoch=1,
            new_epoch=2,
            reason="controlled_work_steal",
            created_at=_now(),
        ),
        OwnershipConflictEvent(
            version="1.0",
            event_id="ownership-conflict-001",
            lease_id="lease-001",
            stale_worker_id="worker-1",
            active_worker_id="worker-2",
            rejected_action="renew_lease",
            summary="stale owner rejected",
            created_at=_now(),
        ),
        ProviderPoolBalancePolicy(
            version="1.0",
            policy_id="provider-balance-policy-001",
            fairness_weight=1.0,
            degradation_penalty=30.0,
            rate_pressure_weight=40.0,
            reservation_pressure_weight=15.0,
            created_at=_now(),
        ),
        ReservationPolicy(
            version="1.0",
            policy_id="reservation-policy-001",
            protected_workloads=["verification", "recovery"],
            reserve_verification_slots=1,
            reserve_recovery_slots=1,
            created_at=_now(),
        ),
        ProviderFairnessPolicy(
            version="1.0",
            policy_id="fairness-policy-001",
            max_host_share=0.6,
            max_worker_share=0.5,
            created_at=_now(),
        ),
        SustainedPressurePolicy(
            version="1.0",
            policy_id="pressure-policy-001",
            pressure_delay_threshold=0.8,
            protect_critical_workloads=["verification", "recovery"],
            created_at=_now(),
        ),
        ProviderFairnessRecord(
            version="1.0",
            record_id="provider-fairness-001",
            provider_name="openai_live",
            worker_allocations={"worker-1": 1, "worker-2": 1},
            host_allocations={"host-a": 1, "host-b": 1},
            fairness_score=1.0,
            reservation_pressure=0.5,
            delayed_tasks=0,
            created_at=_now(),
        ),
        ServicePrincipal(
            version="1.0",
            principal_id="service-principal-001",
            service_name="dispatcher-1",
            service_role="dispatcher",
            scopes=["runtime-admin", "worker-service"],
            status="active",
            created_at=_now(),
        ),
        ServiceCredential(
            version="1.0",
            credential_id="service-credential-001",
            principal_id="service-principal-001",
            token_hash="hash",
            scopes=["runtime-admin"],
            status="active",
            issued_at=_now(),
            expires_at=_now(),
            rotated_from="",
            description="dispatcher credential",
        ),
        ServiceTrustRecord(
            version="1.0",
            trust_id="service-trust-001",
            principal_id="service-principal-001",
            allowed_hosts=["host-a"],
            allow_remote_registration=True,
            created_at=_now(),
        ),
        CredentialRotationRecord(
            version="1.0",
            rotation_id="credential-rotation-001",
            old_credential_id="credential-old",
            new_credential_id="credential-new",
            reason="rotation",
            rotated_at=_now(),
        ),
        AuthFailureEvent(
            version="1.0",
            event_id="auth-failure-001",
            principal_id="service-principal-001",
            action="policy_promote",
            failure_type="forbidden",
            reason="missing scope",
            created_at=_now(),
        ),
        ExecutionReceipt(
            version="1.0",
            receipt_id="receipt-001",
            contract_id=contract.contract_id,
            plan_node_id="node-001",
            actor="Researcher",
            tool_used="file_retrieval",
            input_summary="Read /tmp/requirements.txt",
            output_summary="Retrieved one requirement document",
            artifacts=["artifact-001"],
            evidence_refs=["evidence-001"],
            validation_refs=["validation-001"],
            approval_refs=[],
            status="success",
            timestamp=_now(),
        ),
    ]
    return instances


import pytest


@pytest.mark.parametrize("instance", model_instances())
def test_models_round_trip_and_publish_schema(instance: object) -> None:
    cls = type(instance)
    payload = instance.to_dict()
    restored = cls.from_dict(payload)

    assert restored == instance
    assert payload["version"] == "1.0"

    schema = cls.json_schema()
    assert schema["title"] == cls.__name__
    assert "properties" in schema
